### PR TITLE
global: update the builder to bullseye

### PR DESCRIPTION
**Pull request by david-caro**

### CODE REVIEW

**Review by dhinus — APPROVED** [review]
LGTM!

Not strictly related, but grepping for `buster` I noticed there's a reference in the Dockerfile... can we use a more recent base image there? Feel free to merge this PR and open a separate task for the Dockerfile.

**Comment by blancadesal** [comment]
👍

**Review by blancadesal — APPROVED** [review]

**Comment by david-caro** [comment]
> LGTM!
> 
> Not strictly related, but grepping for `buster` I noticed there's a reference in the Dockerfile... can we use a more recent base image there? Feel free to merge this PR and open a separate task for the Dockerfile.

Good point, I'll upgrade the base dockerfile in another PR :+1:

**Comment by david-caro** [comment]
Done in #9

**Pull request merged**
