### PR TITLE
renamed clinent to client

### PR DESCRIPTION
**Pull request by NdibeRaymond**
see issue #10

### CODE REVIEW

**Comment by david-caro** [comment]
Lgtm

**Review by david-caro — APPROVED** [review]

**Comment by NdibeRaymond** [comment]
ok merging now. unrelated but @david-caro do you know of any example of production pipeline.yaml that can be used to verify that build services works well on toolsbeta?

**Comment by NdibeRaymond** [comment]
> ok merging now. unrelated but @david-caro do you know of any example of production pipeline.yaml that can be used to verify that build services works well on toolsbeta?

tried many things already but non seems to work

**Comment by david-caro** [comment]
> > ok merging now. unrelated but @david-caro do you know of any example of production pipeline.yaml that can be used to verify that build services works well on toolsbeta?
> 
> tried many things already but non seems to work

You can use the toolforge build cli, as your user or as the toolsbeta.test user should work

**Pull request merged**
