### PR TITLE
Test deploy

### PR DESCRIPTION
**Pull request by dhinus**
Bug: [T331339](https://phabricator.wikimedia.org/T331339)

### CODE REVIEW

**Comment by dhinus** [comment]
@david-caro can I get a +1 on this one? :)

**Comment by david-caro** [comment]
:+1: just make sure that the new tag is correct (there's an image with that tag that has the latest code)

**Comment by dhinus** [comment]
That tag was displayed in the output of the build script, so I think it's safe to assume it does exist.

If I wanted to double check, how can I verify if a tag exists in the repo, and what version of the code it contains? I think I can maybe create a temporary pod in Toolforge kubernetes using that image tag, but is there a better/easier way?

**Comment by david-caro** [comment]
> That tag was displayed in the output of the build script, so I think it's safe to assume it does exist.
> 
> If I wanted to double check, how can I verify if a tag exists in the repo

You can try pulling it, something like:
```
docker pull docker-registry.toolforge.org/buildpack-admission:<tag>
```
> , and what version of the code it contains?

That is not that easy :/, I thought about this a bit at some point, and wanted to add a version number or similar to the code so when starting up it would print "build version: blah", so we can compare, but never got around to it.

I think if you built it with the cookbooks should be safe. 

> I think I can maybe create a temporary pod in Toolforge kubernetes using that image tag, but is there a better/easier way?

The above, or running locally also (though that requires a local k8s cluster).

**Comment by dhinus** [comment]
> You can try pulling it, something like:

Ha, I didn't realize the registry was reachable from outside Toolforge/CloudVPS! This worked:

```
docker pull docker-registry.tools.wmflabs.org/toolforge-buildpack-admission-controller:7199a9e
```

> and wanted to add a version number or similar to the code so when starting up it would print "build version: blah",

Yes, this is a nice idea! I think I will skip the image content verification for now, as there is no easy way to test it.

**Comment by dhinus** [comment]
The review is still marked as "pending", I will wait for you to approve it before I merge :)

**Review by david-caro — APPROVED** [review]
:shipit:

**Pull request merged**
